CriptoOrg/CriptoOrg/force-app/main/default/objects/HistoricodePreco__c/HistoricodePreco__c.object-meta.xml
<CustomObject>
    <label>Histórico de Preço</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoricoPrecos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/HistoricodePreco__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>HistoricoPrecos</relationshipLabel>
    <relationshipName>HistoricoPrecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/HistoricodePreco__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um Mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/classes/HistoricoPrecoTriggerHandler.cls
public with sharing class HistoricoPrecoTriggerHandler extends TriggerHandler 
{
    public HistoricoPrecoTriggerHandler() {}

    protected override void afterInsert()
    {
        this.updateMercadoCotacaoAtual();

    }

    private void updateMercadoCotacaoAtual()
    {
        /*Map<id, double> mapPrecos = new Map<id, double>();
        List<Mercado__c> mercadoUpdList = new List<Mercado__c>();

        for (HistoricodePreco__c hp : (List<HistoricodePreco__c>)trigger.new) 
        {
            mapPrecos.put(hp.Mercado__C, hp.Preco__c);
        }

        for (Id mId : mapPrecos.keySet()) 
        {
            mercadoUpdList.add(new Mercado__c(id= mId, CotacaoAtual__c = mapPrecos.get(mId)));
        }
        
        if(mercadoUpdList.size() > 0 && Schema.sObjectType.Mercado__c.isUpdateable())  
        { update mercadoUpdList; }*/

        Map<id, Mercado__c> mapMercado = new Map<id, Mercado__c>();
        for (HistoricodePreco__c hp : (List<HistoricodePreco__c>)trigger.new) 
        {
            mapMercado.put(hp.Mercado__C, new Mercado__C(id = hp.Mercado__c, CotacaoAtual__c = hp.Preco__c));
        }

        update mapMercado.values();

    }
}