CriptoOrg/CriptoOrg/force-app/main/default/objects/HistoricodePreco__c/HistoricodePreco__c.object-meta.xml
<CustomObject>
    <label>Histórico de Preço</label>
    <nameField>
        <displayFormat>HP-{000000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoricoPrecos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/HistoricodePreco__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>HistoricoPrecos</relationshipLabel>
    <relationshipName>HistoricoPrecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/HistoricodePreco__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um Mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/fields/Nivel_Risco__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Risco__c</fullName>
    <label>Nivel Risco</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Médio</fullName>
            </value>
            <value>
                <fullName>Baixo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/classes/Batch_Test.cls
@isTest
public  class Batch_Test {
    public Batch_Test() {

    }

    @isTest
    static void testBatch()
    {
        Mercado__c newMercado = new Mercado__c(id = 'a005e000002zyDEAAY', Name='TST/BRL', Nivel_Risco__c = 'Baixo');

        Double primeiroPreco = 7.50;
        Double ultimoPreco = 14.50;

        List<HistoricodePreco__c> insertHistList = new List<HistoricodePreco__c>();

        while (primeiroPreco <= ultimoPreco) {

            insertHistList.add(new HistoricodePreco__c(
                                                        Mercado__c = newMercado.Id,
                                                        Preco__c = primeiroPreco)
            );

            primeiroPreco += 0.50;
        }

        insert insertHistList;
        
        Test.startTest();

        Database.executeBatch(new ExampleBatchable());
        Database.executeBatch(new ExampleBatchable());

        Test.stopTest();
    }
}