CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}-{MM}-{YYYY}</displayFormat>
        <label>Número da Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <description>Valor unitário da transação.</description>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <description>Quantidade a ser negociada na transação.</description>
    <inlineHelpText>Quantidade a ser negociada na transação.</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Valor total da transação.</description>
    <inlineHelpText>Valor total da transação.</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/classes/OrdemDomain.cls
public with sharing class OrdemDomain 
{
    private Ordem__c ordem;

    public Double  getTotal()
    {
        return ordem.Total__c;
    }

    public OrdemDomain(Ordem__c ordem) 
    {
        this.ordem = ordem;
    }

    public void recalculaTotal()
    {
        if(this.ordem.Preco__c != null && this.ordem.Quantidade__c != null){
            this.ordem.Total__c = this.ordem.Quantidade__c * this.ordem.Preco__c;
        }
        else {
            this.ordem.adderror('Os valores de quantidade e preço não foram preenchidos.');
        }
    }

    public void recalculaQuantidade()
    {
        if(this.ordem.Preco__c != null && this.ordem.Total__c != null)
        {
            this.ordem.Quantidade__c = this.ordem.Total__c / ordem.Preco__c;
        }
        else 
        {
            this.ordem.adderror('Os valores de preço não foi preenchido.');
        }
    }

    public boolean isFieldDifferent(sObjectField field, Ordem__c compareOrdem)
    {
        return this.ordem.get(field) != compareOrdem.get(field);
    }
}