CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}-{MM}-{YYYY}</displayFormat>
        <label>Número da Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <description>Valor unitário da transação.</description>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <description>Quantidade a ser negociada na transação.</description>
    <inlineHelpText>Quantidade a ser negociada na transação.</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Define o tipo de ordem que será gerado.</description>
    <inlineHelpText>Define o tipo de ordem que será gerado.</inlineHelpText>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Valor total da transação.</description>
    <inlineHelpText>Valor total da transação.</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/recordTypes/Venda.recordType-meta.xml
<RecordType>
    <fullName>Venda</fullName>
    <active>true</active>
    <description>Ordem do tipo venda, onde o ativo primário é vendido com intenção de adquirir o ativo secundário.</description>
    <label>Venda</label>
</RecordType>

CriptoOrg/CriptoOrg/force-app/main/default/classes/OrdemTriggerHandler.cls
public with sharing class OrdemTriggerHandler extends TriggerHandler
{
    public OrdemTriggerHandler() {}

    protected override void beforeInsert()
    {
        for (Ordem__c o : (List<Ordem__c>) trigger.New) 
        {
            Ordem__c ordemFoda = o;
            
            /*Caculo do Total*/
            if(ordemFoda.Total__c == null)
            {
                if(ordemFoda.Preco__c != null && ordemFoda.Quantidade__c != null){
                    ordemFoda.Total__c = ordemFoda.Quantidade__c * ordemFoda.Preco__c;
                }
                else {
                    ordemFoda.adderror('Os valores de quantidade e preço não foram preenchidos.');
                }
            }
            //Calculo da quantidade
            else 
            {
                if(ordemFoda.Preco__c != null)
                {
                    ordemFoda.Quantidade__c = ordemFoda.Total__c / ordemFoda.Preco__c;
                }
                else 
                {
                    ordemFoda.adderror('Os valores de preço não foi preenchido.');
                }
            }
            
        }
    }

    protected override void beforeUpdate()
    {
        for (Ordem__c o : (List<Ordem__c>) trigger.New) 
        {
            Ordem__c ordemFoda = o;
            
            Ordem__c ordemFodaOld = (Ordem__c)trigger.oldMap.Get(ordemFoda.Id);

            if(ordemFoda.Quantidade__c != null && ordemFoda.Preco__c != null)
            {
                /*Se o total foi alterado em disparidade com o preco e quantidade*/
                if(ordemFoda.Total__c != ordemFodaOld.Total__c && ordemFoda.Total__c != (ordemFoda.Quantidade__c * ordemFoda.Preco__c))
                {
                    /*Retorna mensagem de erro*/
                    ordemFoda.adderror('O Total não pode ser alterado manualmente.');
                }

                /*Se a quantidade ou o preço foram alterados*/
                if((ordemFoda.Quantidade__c != ordemFodaOld.Quantidade__c)
                    || (ordemFoda.Preco__c != ordemFodaOld.Preco__c))
                {
                    /*Recalcular o Total*/
                    ordemFoda.Total__c = ordemFoda.Quantidade__c * ordemFoda.Preco__c;
                }
            }
            else {
                ordemFoda.adderror('A quantidade ou o preço não foi preenchido.');
            }

            ordemFoda.QuantidadeP__c = ordemFoda.Tipo__c == 'Venda' ? ordemFoda.Quantidade__c * -1 : ordemFoda.Quantidade__c;
        }
    }
}