CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um Mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}-{MM}-{YYYY}</displayFormat>
        <label>Número da Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/CotacaoAtual__c.field-meta.xml
<CustomField>
    <fullName>CotacaoAtual__c</fullName>
    <description>Cotção Atual do Mercado</description>
    <inlineHelpText>Cotção Atual do Mercado</inlineHelpText>
    <label>Cotação Atual</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <description>Valor unitário da transação.</description>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da execução da ordem.</description>
    <inlineHelpText>Status da execução da ordem.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com Lucro</fullName>
            </value>
            <value>
                <fullName>Venda com Prejuizo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/classes/MercadoTriggerHandler.cls
public with sharing class MercadoTriggerHandler extends TriggerHandler 
 {
    public MercadoTriggerHandler() {}
           

    protected override void afterUpdate()
    {
        //this.ExecutaOrdemValdemort();
    }

    
    private void executaOrdemValdemort()
    {
        // Desenvolvedor Salesfoce Voldemorte
        Mercado__c merc = (Mercado__c)trigger.New[0];
        List<Ordem__c> OrdemList = [SELECT Id, Preco__c, Status__c FROM Ordem__c WHERE Mercado__c = :merc.id AND status__c = 'Aguardando'];
        
        for(Ordem__c ord : OrdemList)
        {
            if(ord.status__c == 'Aguardando')
            {
                Mercado__c mercadoOld = (Mercado__c)trigger.oldMap.Get(merc.Id);
                double precoAntigo = mercadoOld.CotacaoAtual__c;
                double precoOrdem = ord.preco__c;
                double preconovo = merc.CotacaoAtual__c;
        
                if((precoOrdem >=precoAntigo && precoOrdem<= preconovo) || (precoOrdem <=precoAntigo && precoOrdem >= preconovo))
                {
                    ord.status__c = 'Executada';
                    update ord;
                }
            }
        }
    }

    private void executaOrdemTalvez()
    {
        Map<id, Ordem__c> mapOrdem = new Map<id, Ordem__c>();

        for (Mercado__c merc : (List<Mercado__c>)trigger.new) {
            
            List<Ordem__c> OrdemList = [SELECT Id, Preco__c, Status__c FROM Ordem__c WHERE Mercado__c =: merc.id AND Status__c = 'Aguardando'];

            for(Ordem__c ord : OrdemList)
            {
                Mercado__c mercadoOld = (Mercado__c)trigger.oldMap.Get(merc.Id);
                double precoAntigo = mercadoOld.CotacaoAtual__c;
                double precoOrdem = ord.preco__c;
                double preconovo = merc.CotacaoAtual__c;
            
                if((precoOrdem >=precoAntigo && precoOrdem<= preconovo) || (precoOrdem <=precoAntigo && precoOrdem >= preconovo))
                {
                    ord.status__c = 'Executada';
                    update ord;
                }    
            }
        }     
    }

    private void executaOrdemFinal()
    {
        List<Mercado__c> mercadoList = [SELECT Id, CotacaoAtual__c, (SELECT Id, Preco__c, Status__c FROM Ordens__r WHERE Status__c = 'Aguardando')
                                        FROM Mercado__c
                                        WHERE Id IN :trigger.newMap.keySet()];

        List<Ordem__c> updateOrdemList = new List<Ordem__c>();

        for(Mercado__c mercado : mercadoList)
        {
            for(Ordem__c ordem : mercado.Ordens__r)
            {
                Mercado__c mercadoOld = (Mercado__c)trigger.oldMap.Get(mercado.Id);
                double precoAntigo = mercadoOld.CotacaoAtual__c;
                double precoOrdem = ordem.preco__c;
                double preconovo = mercado.CotacaoAtual__c;
            
                if((precoOrdem >=precoAntigo && precoOrdem<= preconovo) || (precoOrdem <=precoAntigo && precoOrdem >= preconovo))
                {
                    updateOrdemList.add(new Ordem__c(Id = ordem.Id, Status__c = 'Executada'));
                }    
            }
        }

        update updateOrdemList;
    }

}