CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um Mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Verifica se o mercado está ativo para novas ordems.</description>
    <inlineHelpText>Verifica se o mercado está ativo para novas ordems.</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/fields/ContinuousName__c.field-meta.xml
<CustomField>
    <fullName>ContinuousName__c</fullName>
    <formula>MoedaPrimaria__c +  MoedaSecundaria__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContinuousName</label>
    <type>Text</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/classes/SchedulerGetPrecoHelper.cls
public with sharing class SchedulerGetPrecoHelper {
    public SchedulerGetPrecoHelper() {}

    @future (callout=true)
    public static void AtualizaCotacaoAtualTodosMercadosAtivos()
    {
        Map<string, double> mapSymbolPrice = new Map<string, double>();

        List<BinanceAPI.SymbolPrice> spList = BinanceAPI.getAllMercadoPrice();

        for (BinanceAPI.SymbolPrice sp : spList) {
            mapSymbolPrice.put(sp.symbol,  Double.valueOf(sp.price));
        }

        List<Mercado__c> mercadoList = [SELECT name, ContinuousName__c, CotacaoAtual__c from Mercado__c WHERE Ativo__c = true
                                        AND ContinuousName__c IN : mapSymbolPrice.keySet()];

        for (Mercado__c merc : mercadoList) {
            
            merc.CotacaoAtual__c = mapSymbolPrice.get(merc.ContinuousName__c);
        }


        update mercadoList;

    }
}