CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um Mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}-{MM}-{YYYY}</displayFormat>
        <label>Número da Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/OperacaoMercado__c.field-meta.xml
<CustomField>
    <fullName>OperacaoMercado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define se a compra ou a venda é a preço do mercado.</description>
    <inlineHelpText>Define se a compra ou a venda é a preço do mercado.</inlineHelpText>
    <label>Operação a Mercado?</label>
    <type>Checkbox</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <description>Valor unitário da transação.</description>
    <label>Preço</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <description>Quantidade a ser negociada na transação.</description>
    <inlineHelpText>Quantidade a ser negociada na transação.</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da execução da ordem.</description>
    <inlineHelpText>Status da execução da ordem.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com Lucro</fullName>
            </value>
            <value>
                <fullName>Venda com Prejuizo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Define o tipo de ordem que será gerado.</description>
    <inlineHelpText>Define o tipo de ordem que será gerado.</inlineHelpText>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Valor total da transação.</description>
    <inlineHelpText>Valor total da transação.</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/classes/OrdemController.cls
public with sharing class OrdemController {
    @AuraEnabled
    public static List<Ordem__c> getOrdemLits(string mercadoId){
        List<Ordem__c> ordemList = [SELECT Id, Name, OperacaoMercado__c, Preco__c, Tipo__c, Status__c, Quantidade__c, Total__c, Validade__c 
                                    FROM Ordem__c 
                                    WHERE Mercado__c = :mercadoId
                                    Order by createdDate DESC];
        
        for( Ordem__c ordem : ordemList){
            ordem.Link__c = '/' + ordem.Id;
        }
        return ordemList;
    }
}