CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um Mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <description>Ativo Primário, aquele que é comprado nas operações deste mercado.</description>
    <formula>LEFT(Name, FIND(&quot;/&quot;, Name) - 1)</formula>
    <inlineHelpText>Ativo Primário, aquele que é comprado nas operações deste mercado.</inlineHelpText>
    <label>Moeda Primária</label>
    <type>Text</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Mercado__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <description>Moeda Secundária é o ativo ao qual se vende neste mercado.</description>
    <formula>RIGHT(Name, LEN(Name) - FIND(&quot;/&quot;, Name))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Moeda Secundária é o ativo ao qual se vende neste mercado.</inlineHelpText>
    <label>Moeda Secundária</label>
    <type>Text</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}-{MM}-{YYYY}</displayFormat>
        <label>Número da Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <description>Moeda Primária</description>
    <formula>Mercado__r.MoedaPrimaria__c</formula>
    <inlineHelpText>Moeda Primária</inlineHelpText>
    <label>Moeda Primária</label>
    <type>Text</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/objects/Ordem__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <description>Moeda Secundária</description>
    <formula>Mercado__r.MoedaSecundaria__c</formula>
    <inlineHelpText>Moeda Secundária</inlineHelpText>
    <label>Moeda Secundária</label>
    <type>Text</type>
</CustomField>

CriptoOrg/CriptoOrg/force-app/main/default/classes/BinanceAPI.cls
public class BinanceAPI //with sharing - Obedece os rules do salesforce - without sharing libera o acesso aos dados
{
    @AuraEnabled //Libera o metodo para o JavaSript e o metodo deve ser estatico
    public static string getPrice(string mercadoId)
    {
        Mercado__c mercado = [SELECT Id, MoedaPrimaria__c, MoedaSecundaria__c 
                              FROM Mercado__c  
                              WHERE ID = :mercadoId ];

        string pair = mercado.MoedaPrimaria__c + mercado.MoedaSecundaria__c;
        pair = pair.replace('USD', 'USDT');
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.binance.com/api/v3/ticker/price?symbol=' + pair);
        request.setMethod('GET');
        HttpResponse response = http.send(request);     

        if (response.getStatusCode() == 200) {
            SymbolPrice sp = (SymbolPrice)JSON.deserializeStrict(response.getBody(), SymbolPrice.class);
            
            return sp.price;
        }
        else {
            return 'Erro ao acessar a API da Binance';
        }
    }

    @AuraEnabled(cacheable=true) //Libera o metodo para o JavaSript e o metodo deve ser estatico
    public static List<SymbolPrice> getAllMercadoPrice()
    {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.binance.com/api/v3/ticker/price');
        request.setMethod('GET');
        HttpResponse response = http.send(request);     
        
        if (response.getStatusCode() == 200) {
            List<SymbolPrice> spList = (List<SymbolPrice>)JSON.deserializeStrict(response.getBody(), List<SymbolPrice>.class);
            return spList; 
        }
        else {
            return null;
        }
    }

    @AuraEnabled(cacheable=true) //cacheable=true Armazena o primeiro resultado em cache enquanto a sessão estiver aberta
    public static List<SymbolPrice> getPriceFiltered(string searchKey)
    {
        List<SymbolPrice> assets = getAllMercadoPrice();
        List<SymbolPrice> assetListResponse = new List<SymbolPrice>();

        for (SymbolPrice sp : assets) {
            
            if(sp.symbol.startsWithIgnoreCase(searchKey)){
                assetListResponse.add(sp);
            }
        }

        return assetListResponse;

    }

    public Class SymbolPrice
    {
        @AuraEnabled
        public string symbol {get;set;}

        @AuraEnabled
        public string price {get;set;}
    }

    @AuraEnabled
    public static string getRecordTypeId(String ordemType){
        String rTypeId = Schema.SObjectType.Ordem__c.getRecordTypeInfosByDeveloperName().get(ordemType).getRecordTypeId();
        return rTypeId;

    }
}